# Makefile for linuxtv.org dvb-apps/test/libdvbcfg

binaries = dvbcfg_test

CPPFLAGS += -I../../lib
LDLIBS   += ../../lib/libdvbcfg/libdvbcfg.a

.PHONY: all

all: $(binaries)

include ../../Make.rules
