#!/bin/sh
source scripts/modules.sh
set -e

case "`hostname --short`" in
	eskarina)
#		btopt="card=10"
#		btopt="card=6 remote=1"
		;;
	bogomips)
		saopt="card=7"
		;;
esac

###########################################################################
# unload

# bttv
xrmmod dst
xrmmod bt878
xrmmod ir-kbd-gpio
xrmmod ir-kbd-i2c
xrmmod bttv

# cx88
xrmmod cx88-dvb
xrmmod cx88-blackbird
xrmmod cx8802
xrmmod cx8801
xrmmod cx8800
xrmmod cx88xx

# saa7134
xrmmod saa7134-dvb
xrmmod saa7134-empress
xrmmod saa7134

# saa7146
xrmmod dvb_ttpci
xrmmod saa7146_vv

# dvb
xrmmod or51132
xrmmod cx22702
xrmmod mt352
xrmmod dvb-pll

# common
xrmmod btcx-risc
xrmmod ir-common
xrmmod video-buf-dvb
xrmmod video-buf

# i2c
xrmmod tuner
xrmmod msp3400
xrmmod tvaudio
xrmmod tda9887
xrmmod tveeprom

##########################################################################
# reload

sync; sleep 1;

# common
v4l2basic
#xrmmod video-buf
#xinsmod video-buf debug=0
#xrmmod v4l1-compat
#xinsmod v4l1-compat debug=1

xinsmod tveeprom  debug=0
xinsmod dvb-pll   debug=0
xinsmod btcx-risc debug=0
xinsmod ir-common debug=0 repeat=0
xinsmod tuner     tuner_debug=0
xinsmod tda9887   debug=0 qss=1
xinsmod msp3400   debug=0

# bttv
xinsmod ir-kbd-i2c  debug=0
xinsmod bttv bttv_debug=0 vbi_debug=0 irq_debug=0 \
	fdsr=0 chroma_agc=1 vbibufs=4 irq_iswitch=0 i2c_scan=1 $btopt
xinsmod ir-kbd-gpio debug=0

# cx88
xinsmod cx88xx core_debug=0 audio_debug=0 ir_debug=1 \
	i2c_debug=1 i2c_scan=1
xinsmod cx8800 video_debug=0 vbi_debug=0
xinsmod cx8801
xinsmod cx8802
xinsmod cx88-blackbird

# saa7134
xinsmod saa7134 audio_debug=0 i2c_scan=0 i2c_debug=0 oss=1 $saopt
xinsmod saa7134-empress

# dvb stuff
xinsmod cx22702 debug=0
xinsmod mt352	debug=1
xinsmod or51132
xinsmod tda1004x
xinsmod video-buf-dvb
xinsmod cx88-dvb
xinsmod saa7134-dvb
