.TH alevt-date 1 "February 07, 2010"
.SH NAME
alevt-date \- print out UTC date.
.SH SYNOPSIS
.B alevt-date
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B alevt-date
commands.
.PP
\fBalevt-date\fP is a program to print the UTC date.
.SH OPTIONS
.TP
.B \-d -delta <max_secs>
maximum delta
.TP
.B \-f -format <fmtstr>
time format
.TP
.B \-h -help
print this page
.TP
.B \-s -set
set the system clock
.TP
.B \-t -timeout <seconds>
timeout
.TP
.B \-v -vbi <vbidev>
vbi device /dev/vbi; /dev/vbi0; /dev/video0; /dev/dvb/adapter0/demux0
.TP
.br
.SH SEE ALSO
.BR alevt-cap (1) , alevt (1).
.br
.SH AUTHOR
alevt-date was written by Edgar Toernig <froese@gmx.de>.
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
