/*
 *	SAA7231xx PCI/PCI Express bridge driver
 *
 *	Copyright (C) Manu Abraham <abraham.manu@gmail.com>
 *
 *	This program is free software; you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation; either version 2 of the License, or
 *	(at your option) any later version.
 *
 *	This program is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with this program; if not, write to the Free Software
 *	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef __SAA7231_STR_REG_H
#define __SAA7231_STR_REG_H

#define STREAM_RA_BIGENDIAN				0x0000
#define STREAM_RA_CF_THRESHOLD				0x0004
#define STREAM_RA_VIDEO_LOC_CLGATE			0x0080
#define STREAM_RA_VIDEO_EXT_CLGATE			0x0084
#define STREAM_RA_AUDIO_LOC_CLGATE			0x0088
#define STREAM_RA_AUDIO_EXT_CLGATE			0x008C
#define STREAM_RA_VBI_LOC_CLGATE			0x0090
#define STREAM_RA_TS0_LOC_CLGATE			0x0094
#define STREAM_RA_TS1_LOC_CLGATE			0x0098
#define STREAM_RA_TS0_EXT_CLGATE			0x009C
#define STREAM_RA_TS1_EXT_CLGATE			0x00A0
#define STREAM_RA_TSCA_EXT_CLGATE			0x00A4
#define STREAM_RA_TSOIF0_CLGATE				0x00A8
#define STREAM_RA_TSOIF1_CLGATE				0x00AC
#define STREAM_RA_TSMUX_CLGATE				0x00B0
#define STREAM_RA_AUDIO_LOC_IISMODE			0x0100
#define STREAM_RA_AUDIO_LOC_IISJAPAN			0x0104
#define STREAM_RA_AUDIO_LOC_IISJAPANWIDTH		0x0108
#define STREAM_RA_AUDIO_LOC_STREAM_SEL			0x010C
#define STREAM_RA_AUDIO_LOC_LOST_SAMPLES		0x0110
#define STREAM_RA_AUDIO_LOC_SPDIF_VALLEFT		0x0114
#define STREAM_RA_AUDIO_LOC_SPDIF_VALRIGHT		0x0118
#define STREAM_RA_AUDIO_LOC_SPDIF_COUNT_PARLEFT		0x011C
#define STREAM_RA_AUDIO_LOC_SPDIF_COUNT_PARRIGHT	0x0120
#define STREAM_RA_AUDIO_LOC_SPDIF_CHSTAT_LEFT0		0x0124
#define STREAM_RA_AUDIO_LOC_SPDIF_CHSTAT_LEFT1		0x0128
#define STREAM_RA_AUDIO_LOC_SPDIF_LOCK			0x012C
#define STREAM_RA_AUDIO_EXT_IISMODE			0x0180
#define STREAM_RA_AUDIO_EXT_IISJAPAN			0x0184
#define STREAM_RA_AUDIO_EXT_IISJAPANWIDTH		0x0188
#define STREAM_RA_AUDIO_EXT_STREAM_SEL			0x018C
#define STREAM_RA_AUDIO_EXT_LOST_SAMPLES		0x0190
#define STREAM_RA_AUDIO_EXT_SPDIF_VALLEFT		0x0194
#define STREAM_RA_AUDIO_EXT_SPDIF_VALRIGHT		0x0198
#define STREAM_RA_AUDIO_EXT_SPDIF_COUNT_PARLEFT		0x019C
#define STREAM_RA_AUDIO_EXT_SPDIF_COUNT_PARRIGHT	0x01A0
#define STREAM_RA_AUDIO_EXT_SPDIF_CHSTAT_LEFT0		0x01A4
#define STREAM_RA_AUDIO_EXT_SPDIF_CHSTAT_LEFT1		0x01A8
#define STREAM_RA_AUDIO_EXT_SPDIF_LOCK			0x01AC
#define STREAM_RA_TS_SEL				0x0200
#define STREAM_RA_TS_OUT_CONFIG				0x0204
#define STREAM_RA_PS2P_0_EXT_CFG			0x0208
#define STREAM_RA_PS2P_1_EXT_CFG			0x020C
#define STREAM_RA_PS2P_CA_EXT_CFG			0x0210
#define STREAM_RA_TOP_SCR_WIN_BASE			0x0400
#define STREAM_RA_SPARE					0x0800



#define STREAM_TSOIF_BASE				0x2000
#define STREAM_TSOIF_OFFST				0x1000
#define STREAM_TSOIF_OFFSET(__ch)			(STREAM_TSOIF_BASE + (STREAM_TSOIF_OFFST * __ch))

#define STREAM_TSOIF_RA_CONTROL(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x008)
#define STREAM_TSOIF_RA_PROPERTIES(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x010)
#define STREAM_TSOIF_RA_PACKET_LENGTH(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x018)
#define STREAM_TSOIF_RA_START_TIME(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x020)
#define STREAM_TSOIF_RA_BUFFER_START(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x028)
#define STREAM_TSOIF_RA_BUFFER_STOP(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x030)
#define STREAM_TSOIF_RA_BUFFER_WPTR(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x038)
#define STREAM_TSOIF_RA_BUFFER_RPTR(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x040)
#define STREAM_TSOIF_RA_BUFFER_CONTENT(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x048)
#define STREAM_TSOIF_RA_THRESHOLD(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x050)
#define STREAM_TSOIF_RA_ERROR_RD(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x058)
#define STREAM_TSOIF_RA_SCR_SEL(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x060)
#define STREAM_TSOIF_RA_DBG_IN(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x068)
#define STREAM_TSOIF_RA_DBG_RD(__ch)			(STREAM_TSOIF_OFFSET(__ch) + 0x070)
#define STREAM_TSOIF_RA_INT_ENABLE_CLR(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7D8)
#define STREAM_TSOIF_RA_INT_ENABLE_SET(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7DC)
#define STREAM_TSOIF_RA_INT_ENABLE(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7E0)
#define STREAM_TSOIF_RA_INT_STATUS(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7E4)
#define STREAM_TSOIF_RA_INT_STATUS_CLR(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7E8)
#define STREAM_TSOIF_RA_INT_STATUS_SET(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7EC)
#define STREAM_TSOIF_RA_SOFT_RESET(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7F4)
#define STREAM_TSOIF_RA_POWER_DOWN(__ch)		(STREAM_TSOIF_OFFSET(__ch) + 0x7F8)


#endif /* __SAA7231_STR_REG_H */
